"""add task timestamps

Revision ID: 63f028fabb3d
Revises: 2e74b9ae36ce
Create Date: 2026-03-05 19:18:49.413808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f028fabb3d'
down_revision: Union[str, Sequence[str], None] = '2e74b9ae36ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
